### ISSUE TITLE
As an admin, I want emergency notifications about fires to be automatically sent to people in danger

### ISSUE THREAD

**Issue by danhon** [VeryLittleGravitas/CDTADPQ#105]
Acceptance criteria:

1. Get regularly updated fire data from USGS
2. Translate USGS fire data lat-long into a zipcode
3. Look for users within a buffer (e.g. 50-100km) of a fire zipcode
4. Automatically send an emergency notification to the users inside the buffer area
5. Do not send repeated notifications

**Comment by danhon** [comment]
This still needs to be hooked up to:

1. Automatically send the appropriate SMS messages to users
2. Automatically send the appropriate email notifications to users

**Comment by danhon** [comment]
I have written up our discussion about the different types of notification our prototype supports:

https://github.com/VeryLittleGravitas/CDTADPQ/wiki/Design-exploration#emergency-notifications

**Comment by migurski** [comment]
I configured Heroku scheduler to send automatic notifications at the top of every hour.
