### ISSUE TITLE
Task: Put our persona documentation on the Wiki

### ISSUE THREAD

**Issue by danhon** [VeryLittleGravitas/CDTADPQ#106]
See: https://github.com/VeryLittleGravitas/CDTADPQ/wiki/Personas

**Comment by danhon** [comment]
@phae and @kerrching please review Wiki documentation to make sure it reflects our work:

https://github.com/VeryLittleGravitas/CDTADPQ/wiki/Personas

**Comment by kerrching** [comment]
👍 from me

**Comment by phae** [comment]
+1
