### ISSUE TITLE
As an admin of the service, I want to send emergency notifications so people know when they are in danger

### ISSUE THREAD

**Issue by danhon** [VeryLittleGravitas/CDTADPQ#41]
Acceptance Criteria:

1. An admin user must be able to log into an administrative area
2. The admin user must be able to view emergency data on a map to identify affected areas see #60 
3. The admin user can create an emergency notification that will be sent to all users 
4. The emergency notification must fit within the SMS limit of 140 characters

Notes:
For the purposes of the MVP for the prototype, these notifications go to all users. The prototype description does not require that admins publish notifications to specific geographical areas.

Relevant prototype description:

> In addition, the working prototype will provide the authorized administrative users with the ability to publish notifications and track, and analyze and visualize related data. The working prototype does not need to implement any authentication or authorization against an external directory or authentication mechanism.
--------

Template: https://github.com/VeryLittleGravitas/CDTADPQ/blob/master/CDTADPQ/web/templates/send-alert.html

**Comment by phae** [comment]
The prototype description doesn't seem to need an auth, but since we're probably going to put it live, we might want to at least slap a password the /admin URLs.

Templates already set up here:
https://vlg-ctdadpq.herokuapp.com/admin - View map of current situation
https://vlg-ctdadpq.herokuapp.com/send-alert - Configure the alert
https://vlg-ctdadpq.herokuapp.com/sent - Alert sent

**Comment by danhon** [comment]
Re-opened after discussion with @pui because it needs wiring up.

**Comment by danhon** [comment]
I have written up our discussion about the different kinds of notifications our prototype supports:

https://github.com/VeryLittleGravitas/CDTADPQ/wiki/Design-exploration#emergency-notifications
