### ISSUE TITLE
As a user of the service, I want to receive notifications based on the geo-location of my phone so that I receive relevant notifications

### ISSUE THREAD

**Issue by danhon** [VeryLittleGravitas/CDTADPQ#52]
Acceptance criteria:

1. At any time, a user can update the location field for their profile with the geo-location of their phone

Relevant prototype requirement description: 

> The working prototype will be an application that will allow California residents to establish and manage their profile and receive emergency and non-emergency notifications via email, Short Message Service (SMS), and/or push notification based on the location and contact information provided in their profile and/or the geo-location of their cellphone if they have opted in for this service.

**Comment by migurski** [comment]
Currently, we use the browser geolocation API during the signup process. See also: https://github.com/VeryLittleGravitas/CDTADPQ/pull/65

We do not yet allow a user to add or change their signup — would geolocation need to be used there as well, behind an "add a zip code" feature?
