### ISSUE TITLE
As a user of the service, I want to choose which notifications I receive, so I can be alerted to the events I'm interested in.

### ISSUE THREAD

**Issue by kerrching** [VeryLittleGravitas/CDTADPQ#58]
Acceptance Criteria: 
1. All users must receive emergency notifications
2. Emergency notifications are notifications that are:
2.1 Fire emergency notifications that are automatically triggered
2.2 Manual emergency notifications that are published by an admin
3. At any time, users can choose to receive additional, non-emergency notifications
4. The choice to receive non-emergency notifications shows an example of a non-emergency notification
 
@phae given the prototype description, I *think* we should group all emergency notifications together for now, to make things simpler: users just sign up for emergency notifications, and those are any fire/flood/tsunami/earthquake notifications.  My thinking here is that for a given location, we want users to receive all relevant notifications.

Assumption: users want to receive all emergency notifications for any area they're interested in, and don't want/need overhead of deciding what kind of emergency notification to receive. ie: "you didn't send me a fire notification because I didn't select fire?"

---------

See the profile template: https://github.com/VeryLittleGravitas/CDTADPQ/blob/master/CDTADPQ/web/templates/profile.html

**Comment by phae** [comment]
@kerrching @danhon Ah! I see what you're saying. Yeah, that would certainly simplify things. Good idea, will update the UIs accordingly.

Question though - your acceptance criteria distinguishes between emergency and non-emergency - if we're not asking them what they want to know about, then to our system, everything becomes an emergency and there's no differentiation.  So, 5, 6 and 7 wouldn't be things anymore. Is that right?

**Comment by phae** [comment]
Or, perhaps I'm misinterpreting. Do you both think non-emergencies are things written by the admin, but not tied to an event we're getting in the data set?  If so, then I understand again. :)

**Comment by danhon** [comment]
@phae so the prototype requirements say that users need to be able to say whether they want to receive non-emergency notifications. I think we can argue that 5, 6, 7 could be stubbed. There's no requirement I see in the the prototype description that the admin be able to send a non-emergency notification.

**Comment by danhon** [comment]
@phae ok, so the prototype requirement says "the working prototype will provide the authorized administrative users with the ability to publish notifications" and doesn't differentiate between emergency or non-emergency notifications.  I think we could argue that the functionality for sending a non-emergency notification can be stubbed.

**Comment by phae** [comment]
👍  OK, got it. I'll stub in everything I think this ticket needs in the UIs, then pass this issue over to @pui or @migurski.
