### ISSUE TITLE
As a user of the service, I want to choose how I receive notifications, so I am alerted to events in the right way for me

### ISSUE THREAD

**Issue by danhon** [VeryLittleGravitas/CDTADPQ#59]
Acceptance Criteria:

1. All users receive notifications by SMS by default
2. Delivery preferences apply to all types of notification (emergency and non-emergency)

Choosing to receive notifications by email 
1. Users can choose to receive notifications by email by adding an email address to their profile
2. If a user adds an email address to the profile, the service sends a verification email and the user clicks on a link in that email to verify their address
3. If an email address is verified, the user can choose to have notifications delivered by email instead of SMS

Choosing to receive notifications by push notification
1. Users can choose to receive notification by mobile device push notification

**Comment by migurski** [comment]
Things left to do here:

- Add UI words to tell people that we'll email instead of SMS
- All the push notification crap (seriously?)

**Comment by migurski** [comment]
I am declaring this Good Enough For Now, and moving the push notifications to new issue https://github.com/VeryLittleGravitas/CDTADPQ/issues/70.
