### ISSUE TITLE
As an admin, I want to visualize [related data] so that I can decide what notifications to publish

### ISSUE THREAD

**Issue by danhon** [VeryLittleGravitas/CDTADPQ#60]
As a team, we must decide what related data means for this user story. Related data at a minimum is the datasets prescribed by the prototype requirements in the RFI. 

Acceptance criteria:

1. Admin users must be able to view the following emergency data on a map:
1.1 Active Fire Boundaries data
1.2 River Gauge (current and forecast) data
1.3 Weather Hazards data
1.4 Earthquakes data
1.5 Tusnami data
1.6 Interior Geospatial Emergency Management System data
2. Admin users must be able to view the locations of users on a map:
2.1 The admin must be able to see the number of users for any zipcode where there are users

**Comment by phae** [comment]
I put a holding page up here: https://vlg-ctdadpq.herokuapp.com/stats

I wonder if this should also be available to the public - even if it's got slightly less information than an admin would see. The public may be just as interested to know how many alerts the State has sent, and on what topics etc.

**Comment by phae** [comment]
I put a holding page up here - which is really an extension of this ticket (it's the post-alert bits): https://vlg-ctdadpq.herokuapp.com/stats

I wonder if this should also be available to the public - even if it's got slightly less information than an admin would see. The public may be just as interested to know how many alerts the State has sent, and on what topics etc.
