### ISSUE TITLE
As an admin, I want to send non-emergency notifications so that users receive relevant non-emergency information

### ISSUE THREAD

**Issue by danhon** [VeryLittleGravitas/CDTADPQ#90]
Acceptance Criteria:

1. An admin can log in 
2. An admin can send a non-emergency notification, that does not require data from any emergency data sources as a pre-requisite
3. The non-emergency message is sent to registered users with the following criteria:
3.1 **have opted-in to receive non-emergency message**

For the avoidance of doubt, non-emergency messages are sent to **all users who have opted-in to receive non-emergency messages regardless of location**.

---

An example of a non-emergency notification would be: "Today is polling day! Everyone remember to vote!" 

We expect that the non-emergency notification functionality would be iterated upon based on user feedback as non-emergency broadcast messages to all users are of questionable value (without us having validated this assumption) but an example usage that would require geofencing would be notifying users about school closures due to inclement weather.

**Comment by phae** [comment]
There is related work for this in this un-merged PR: #61

**Comment by danhon** [comment]
Acceptance Criteria:

1. An admin can log in 
2. An admin can send a non-emergency notification, that does not require data from any emergency data sources as a pre-requisite
3. The non-emergency message is sent to all registered users 

---

An example of a non-emergency notification would be: "Today is polling day! Everyone remember to vote!" 

We expect that the non-emergency notification functionality would be iterated upon based on user feedback as non-emergency broadcast messages to all users are of questionable value (without us having validated this assumption) but an example usage that would require geofencing would be notifying users about school closures due to inclement weather.

**Comment by danhon** [comment]
I have written up our discussion about the different types of notification our prototype supports:

https://github.com/VeryLittleGravitas/CDTADPQ/wiki/Design-exploration#emergency-notifications

**Comment by danhon** [comment]
I updated the acceptance criteria:

3. The non-emergency message is sent to all registered users who have opted-in to receive non-emergency notifications, regardless of location
