### ISSUE TITLE
As an admin, I want to track [related data] so that I can analyze it

### ISSUE THREAD

**Issue by danhon** [VeryLittleGravitas/CDTADPQ#91]
Acceptance Criteria:

For an admin to track data so it can be analyzed, the prototype must: 

1. For each published notification, show the number of users the notification was sent to
2. Display the number of registered users and their profile location

**Comment by phae** [comment]
Template made for this: https://github.com/VeryLittleGravitas/CDTADPQ/pull/119

**Comment by danhon** [comment]
@migurski is supposed to do:

2. Display the number of registered users and their profile location

**Comment by migurski** [comment]
I am picking this up to finish part two.
