### ISSUE TITLE
Task: Deployed their software in an open source container, such as Docker

### ISSUE THREAD

**Issue by danhon** [VeryLittleGravitas/CDTADPQ#95]
This is required to fulfill the following technical requirement:

r. Deployed their software in an open source container, such as Docker (i.e., utilized operating-system-level virtualization);

By doing this, we will also have the answers for: 

p. Setup or used configuration management;

**Comment by migurski** [comment]
Dockerfile now exists in `Dockerfile`. Needs documentation; reassigning to @danhon.

**Comment by danhon** [comment]
I am building a Docker image based on the Docker file locally.

**Comment by danhon** [comment]
Documentation as it exists so far is here:

https://github.com/VeryLittleGravitas/CDTADPQ/wiki/Use-the-Docker-image

**Comment by danhon** [comment]
Waiting on @migurski to help with documentation.

**Comment by migurski** [comment]
Completed the docs.
